name: 'Docker Login Build Tag Push'

author: 'Danstan Onyango - Zemuldo'

description: 'Build, Tag and Push images to Registry'

inputs:
  image_name: 
    description: "Docker Image Name"
  image_tag:
    description: "Docker Image Tag"

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.image_name }}
    - ${{ inputs.image_tag }}
    - ${{ inputs.docker_dir }}
    - ${{ inputs.docker_target }}

branding:
  icon: 'upload-cloud'  
  color: 'blue'
